const StatusEnum = Object.freeze({
    PENDENTE: "PENDENTE",
    BLOQUEADO: "BLOQUEADO",
    EM_ANDAMENTO: "EM_ANDAMENTO",
    EXPIRADO: "EXPIRADO",
    CONCLUIDO: "CONCLUIDO",
    CONCLUIDO_COM_ATRASO: "CONCLUIDO_COM_ATRASO"
});

export default StatusEnum;